[2022-08-22 16:50:51,008] {{taskinstance.py:655}} INFO - Dependencies all met for <TaskInstance: hello_nifi.failure_logging 2022-08-22T16:50:19.389081+00:00 [queued]>
[2022-08-22 16:50:51,013] {{taskinstance.py:655}} INFO - Dependencies all met for <TaskInstance: hello_nifi.failure_logging 2022-08-22T16:50:19.389081+00:00 [queued]>
[2022-08-22 16:50:51,014] {{taskinstance.py:866}} INFO - 
--------------------------------------------------------------------------------
[2022-08-22 16:50:51,014] {{taskinstance.py:867}} INFO - Starting attempt 1 of 1
[2022-08-22 16:50:51,015] {{taskinstance.py:868}} INFO - 
--------------------------------------------------------------------------------
[2022-08-22 16:50:51,316] {{taskinstance.py:887}} INFO - Executing <Task(PythonOperator): failure_logging> on 2022-08-22T16:50:19.389081+00:00
[2022-08-22 16:50:51,319] {{standard_task_runner.py:53}} INFO - Started process 492 to run task
[2022-08-22 16:50:51,350] {{logging_mixin.py:112}} INFO - Running %s on host %s <TaskInstance: hello_nifi.failure_logging 2022-08-22T16:50:19.389081+00:00 [running]> myairflow
[2022-08-22 16:50:51,358] {{logging_mixin.py:112}} INFO - something failed... cleaning up.
[2022-08-22 16:50:51,358] {{python_operator.py:114}} INFO - Done. Returned value was: None
[2022-08-22 16:50:51,361] {{taskinstance.py:1048}} INFO - Marking task as SUCCESS.dag_id=hello_nifi, task_id=failure_logging, execution_date=20220822T165019, start_date=20220822T165051, end_date=20220822T165051
[2022-08-22 16:51:01,005] {{logging_mixin.py:112}} INFO - [2022-08-22 16:51:01,005] {{local_task_job.py:103}} INFO - Task exited with return code 0
